describe('Secret Menu with Cypress Studio', () => {
  beforeEach(() => {
    cy.visit('/secret-menu');
  });

  it('does stuff generated by Cypress Studio', () => {});

  /* ==== Test Created with Cypress Studio ==== */
  it('starbucks', function() {
    /* ==== Generated with Cypress Studio ==== */
    cy.get('#minimum-rating-visibility').click();
    cy.get('#restaurant-visibility > label.block').click();
    cy.get('#restaurant-visibility-filter').select('Starbucks');
    /* ==== End Cypress Studio ==== */
  });
});
